version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "tailor-template"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1i4n3b7ti0sxk"
s3_prefix = "tailor-template"
region = "eu-central-1"
profile = "private"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TemplateBucketName=\"less-templates-eugen\""

