AWSTemplateFormatVersion: 2010-09-09
Description: tailor-lambda

Transform: AWS::Serverless-2016-10-31
Parameters:
  TemplatesBucketName:
    Description: Name of the s3 bucket holding the templates
    Type: String

Resources:

  ServeTailorTemplatesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: handler function
      Policies:
        - AWSLambdaBasicExecutionRole
        - S3CrudPolicy:
            BucketName: "*"
      Environment:
        Variables:
          TEMPLATES_BUCKET_NAME: !Ref TemplatesBucketName
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{template}
            Method: GET

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
